cd('C:\Users\Jonny\Docs\Uni Stuff\Project\fbaInfluenza');
addpath(genpath('C:\Users\Jonny\Docs\Uni Stuff\Project\fbaInfluenza'));
load('HGNCIDs');
load('GSE49840.mat');
load('AgilentSurePrintG3GE8x60kv2probe.mat');
load('recon2.2.mat');
load('HGNCindexArray.mat');
load('HGNCarray');
load('GSE49840Values');
load('GSE49840NormalisedValues');